version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" 
    schedule:
      interval: "daily"
    # open-pull-requests-limit: 10   # opcional: limite de PRs abiertas
    # allow:                        # opcional: solo dependencias directas
    #   - dependency-type: "direct"
